name: core
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  equatable: ^2.0.5
  xml2json: ^6.2.0
  http: ^0.13.5
  rxdart: ^0.27.7
  xml: ^6.3.0
  uuid: ^3.0.7

dev_dependencies:
  # Package depends on http 0.13.5 until migration request to 1.1.0 is merged - import commented out
  # dart_code_metrics: ^5.7.5
  dart_code_metrics_presets: ^2.1.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
