name: core
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:

  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  equatable: ^2.0.5
  xml2json: ^6.2.0
  http: ^1.1.0
  rxdart: ^0.27.7
  xml: ^6.3.0
  uuid: ^4.0.0
  postgres: ^2.6.2
  logger: ^2.0.2
  encrypt: ^5.0.3
  yookassa_payments_flutter: ^1.1.1

dev_dependencies:
  dart_code_metrics_presets: ^2.3.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
