name: common
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  easy_autocomplete: ^1.6.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_localizations:
    sdk: flutter
  intl: 0.18.0

dev_dependencies:
  # Package depends on http 0.13.5 until migration request to 1.1.0 is merged - import commented out
  dart_code_metrics: ^5.7.5
  dart_code_metrics_presets: ^1.0.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:

  generate: true

  assets:
    - assets/vector/

  fonts:
    - family: Avtovas
      fonts:
        - asset: assets/fonts/Avtovas_Normal.ttf
          style: normal
        - asset: assets/fonts/Avtovas_Bold.ttf
          weight: 500
        - asset: assets/fonts/Avtovas_W_700.ttf
          weight: 700
        - asset: assets/fonts/Avtovas_Italic.ttf
          style: italic

